### ISSUE TITLE
Structuring this repository

### ISSUE THREAD

**Issue by apeltzer** [nf-core/test-datasets#1]
Can we maybe have a quick discussion on whether such a structure would be appropriate?:

```
extra/<pipeline-name>/...
reference_data/<pipeline-name>/...
testdata/<pipeline-name>/...
``` 
`Extra` would keep e.g. BED/PED files for certain pipelines which should be kind of unique per pipeline. 
`Reference_data` could keep reference genome data, and can be shared in my opinion (does that make sense?)
`testdata` could keep per-pipeline testdata

What do others think about these points? @nf-core/admin  ?

**Comment by apeltzer** [comment]
Cross linking my PR that I#d like to use as a first test point:
https://github.com/nf-core/ExoSeq/pull/13

**Comment by apeltzer** [comment]
One particular problem I see is that the repository might become too big for hosting on GitHub. 
Do you think that could be a problem? 
https://help.github.com/articles/what-is-my-disk-quota/
Branches sound great - I suppose that should keep things clean

**Comment by MaxUlysse** [comment]
And we should list the different branches in the README.md on master

**Comment by ewels** [comment]
The branches idea came from @pditommaso - that way we can have a git submodule for a single test dataset without having to download the test data for _every_ nf-core pipeline. Each branch should be an orphan - `master` can just have a readme with instructions.

Total repository size could become an issue, yes. I'm not sure how LFS really helps - GitHub [still has the 1GB limit](https://help.github.com/articles/about-storage-and-bandwidth-usage/), even with LFS..? I guess we just need to keep things slim!

**Comment by MaxUlysse** [comment]
I think it might be overkill for test data.
But we can probably set up a script to pull all branches and generate the README, even with the md5sum ;-)

**Comment by tiagochst** [comment]
Git LFS would help to add files over 100MB, without git LFS, the commit will be blocked for files over 100MB. I believe there is a warning for files between 50MB and 100MB saying the max is 50MB.

**Comment by MaxUlysse** [comment]
By the way, we set this up for Sarek:
https://github.com/SciLifeLab/Sarek-data

I think you'll all see where the inspiration comes from ;-)

**Comment by apeltzer** [comment]
Regarding git lfs: yes it would help but we should try to keep things as small as possible in all cases anyways. The Sarek way looks fine to me and the ExoSeq pipeline will do the same in the next days once I’m back at work :)

**Comment by anfederico** [comment]
Looking forward to this! Would be an amazing resource. I have a good set I've been using for scRNA-seq pipelines.

**Comment by ewels** [comment]
I think we can close this issue now - we've started building different branches for the different pipelines and it seems to be working well!
