### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by luantunez** [nf-core/test-datasets#301]
Hello and thank you for sharing the datasets. I am not being able to download the resources and testdata folders with the 
git clone https://github.com/nf-core/test-datasets.git command
Could you help me? Thank you in advance

**Comment by jfy133** [comment]
Each pipeline has it's own branch that contains the data, there is no data in `master`.

![image](https://user-images.githubusercontent.com/17950287/128140408-a80e21a3-bc7d-440e-a828-5cae60607f4f.png)

e.g. try `git switch sarek`, and possibly `git pull` to get th latst changs.

**Comment by maxulysse** [comment]
I'd recommend doing:
```
git clone --single-branch --branch sarek https://github.com/nf-core/test-datasets.git
```
to download only a single branch when cloning the repo
