### ISSUE TITLE
Rename spatialomics to imaging for modules branch

### ISSUE THREAD

**Issue by adamjtaylor** [nf-core/test-datasets#815]
As [discussed on slack](https://nfcore.slack.com/archives/C02L5UB4Y9G/p1678782132307509?thread_ts=1677879744.794279&cid=C02L5UB4Y9G), @FloWuenne and @jmuhlich have proposed to rename the [spatialomics directory](https://github.com/nf-core/test-datasets/tree/modules/data/spatialomics) in the [modules branch](https://github.com/nf-core/test-datasets/tree/modules/) to `imaging`. This better reflects the specific use cases for image registration, segmentation  and quantification.

This will impact only two modules that are currently in development and will need to point towards this new directory

- https://github.com/nf-core/modules/pull/2875
- https://github.com/nf-core/modules/pull/2894

**Comment by jmuhlich** [comment]
Will be closed by #821

**Comment by adamjtaylor** [comment]
Pending action:
> Can you also open a quick PR that updates the tests/config/test_data.config file in the modules repo so we don't break any tests for modules dependent on the spatialomics data?
